// Copyright 2025 Substrate Systems OÜ
// SPDX-License-Identifier: Apache-2.0

package nix

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/Artexis10/endstate/go-engine/internal/manifest"
)

// defaultStateVersion is the home-manager state version the engine injects when
// the user does not override it via ENDSTATE_HM_STATE_VERSION. home-manager only
// WARNS on a mismatch (confirmed against real home-manager), so a pinned default
// is safe; the env knob mirrors the ENDSTATE_*_PIN convention.
const defaultStateVersion = "24.05"

// HomeIdentity is the machine identity the engine injects into a generated flake
// so the user's home.nix never hardcodes machine-specific values (the moat).
// home-manager errors loudly if these mismatch the running user/$HOME, so the
// engine is the right owner.
type HomeIdentity struct {
	Username     string
	HomeDir      string
	StateVersion string
}

// homeIdentityFn resolves the identity the engine injects. It is a package var so
// tests can inject a deterministic identity without touching the host.
var homeIdentityFn = defaultHomeIdentity

// defaultHomeIdentity reads identity from the running user, the OS home dir, and
// the state-version env knob (ENDSTATE_HM_STATE_VERSION, default
// defaultStateVersion).
func defaultHomeIdentity() (HomeIdentity, error) {
	u, err := user.Current()
	if err != nil {
		return HomeIdentity{}, fmt.Errorf("resolve current user: %w", err)
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return HomeIdentity{}, fmt.Errorf("resolve home directory: %w", err)
	}
	sv := os.Getenv("ENDSTATE_HM_STATE_VERSION")
	if sv == "" {
		sv = defaultStateVersion
	}
	return HomeIdentity{Username: u.Username, HomeDir: home, StateVersion: sv}, nil
}

// nixSystem returns the Nix system double for the host (e.g. "x86_64-linux"),
// derived from the Go runtime so the generated flake pins pkgs to the host system
// without an impure `builtins.currentSystem`.
func nixSystem() string {
	arch := runtime.GOARCH
	switch arch {
	case "amd64":
		arch = "x86_64"
	case "arm64":
		arch = "aarch64"
	case "386":
		arch = "i686"
	}
	return arch + "-" + runtime.GOOS
}

// HomeFlakeSpec is the pure input to the home-manager flake generator. The engine
// fills identity (Username/HomeDir/StateVersion), the host System, and the input
// pins (NixpkgsPin/HomeManagerPin); the user supplies only their home.nix, copied
// in beside the flake and referenced as ./home.nix.
type HomeFlakeSpec struct {
	Name           string   // homeConfigurations.<Name> and the flakeref attribute
	Username       string   // injected home.username
	HomeDir        string   // injected home.homeDirectory
	StateVersion   string   // injected home.stateVersion
	System         string   // nixpkgs.legacyPackages.<System>
	NixpkgsPin     string   // inputs.nixpkgs.url
	HomeManagerPin string   // inputs.home-manager.url
	ExtraModules   []string // extra ./<file> module refs staged beside the flake (e.g. ./secrets.nix)
}

// renderHomeFlake renders a plain, commented flake.nix that wraps the user's
// home.nix (copied in as ./home.nix) with pinned nixpkgs + home-manager (nixpkgs
// follows) and the engine-injected identity. Pure: same spec → same text. The
// output is deliberately readable + commented — invisible by default, inspectable
// on demand (a power user can `nix run home-manager -- switch --flake <dir>`).
//
// The user's config is COPIED IN and referenced relatively (./home.nix), NOT by
// absolute path: home-manager evaluates the flake in pure mode, which forbids
// reading absolute paths outside the flake tree. Copying it in also makes the
// generated directory a complete, self-contained, ejectable flake.
func renderHomeFlake(s HomeFlakeSpec) string {
	// Extra modules (e.g. ./secrets.nix) are appended to the modules list, each
	// indented to match the generated list. They are staged beside the flake and
	// referenced relatively (pure-eval-safe).
	var extra strings.Builder
	for _, m := range s.ExtraModules {
		extra.WriteString("\n        " + m)
	}
	return fmt.Sprintf(`{
  # GENERATED BY ENDSTATE — do not edit by hand.
  # This flake wraps your home.nix (copied in beside it as ./home.nix) so you only
  # write home-manager configuration, never the surrounding flake plumbing. It is
  # regenerated on each `+"`apply`"+`; your home.nix is the source of truth. The
  # directory is a complete flake: a power user can take it over and run
  #   nix run home-manager -- switch --flake .#%[1]s
  # Inputs are pinned by the engine (override via ENDSTATE_NIXPKGS_PIN /
  # ENDSTATE_HOME_MANAGER_PIN); identity is injected by the engine.
  description = "Endstate-generated home-manager configuration for %[1]s";

  inputs = {
    nixpkgs.url = "%[6]s";
    home-manager.url = "%[7]s";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { nixpkgs, home-manager, ... }: {
    homeConfigurations."%[1]s" = home-manager.lib.homeManagerConfiguration {
      pkgs = nixpkgs.legacyPackages."%[5]s";
      modules = [
        # Your configuration (copied in from the path your manifest referenced).
        ./home.nix
        # Machine identity injected by Endstate — keep this out of your home.nix.
        {
          home.username = "%[2]s";
          home.homeDirectory = "%[3]s";
          home.stateVersion = "%[4]s";
        }%[8]s
      ];
    };
  };
}
`, s.Name, s.Username, s.HomeDir, s.StateVersion, s.System, s.NixpkgsPin, s.HomeManagerPin, extra.String())
}

// GenerateHomeFlake renders the wrapper flake for the user's home.nix at
// configPath and writes a self-contained, inspectable flake to
// <stateDir>/home-manager/<name>/ — flake.nix plus a verbatim copy of home.nix —
// returning the <dir>#<name> flakeref the existing ActivateHome consumes. The
// config name (and state subdir) is the current username, matching the injected
// home.username and the home-manager convention.
//
// The directory PERSISTS (it is not a wiped temp): the user's home.nix is the
// source of truth and the generated flake is regenerated each run, but the
// directory stays so it is discoverable, readable, and ejectable. Any flake.lock
// Nix writes there on activation is left in place (within-machine reproducibility
// without the engine owning a lock).
func GenerateHomeFlake(stateDir, configPath string, secrets []manifest.HomeManagerSecret) (string, error) {
	body, err := os.ReadFile(configPath)
	if err != nil {
		return "", fmt.Errorf("read home-manager config %q: %w", configPath, err)
	}
	// Copy the user's config in (pure-eval forbids an absolute path module ref).
	return writeHomeFlake(stateDir, body, nil, secrets)
}

// writeHomeFlake writes a self-contained, inspectable flake to
// <stateDir>/home-manager/<name>/ — flake.nix, the home.nix content, and any extra
// files to stage (relative path within the flake dir → content) — and returns the
// <dir>#<name> flakeref. It is the shared core of GenerateHomeFlake (config-file
// input) and GenerateHomeFlakeFromSettings (declarative catalog). <name> (and the
// state subdir) is the current username, matching the injected home.username.
//
// The directory PERSISTS and is regenerated each run, so it stays discoverable,
// readable, and ejectable; any flake.lock Nix writes there on activation is left
// in place (within-machine reproducibility without the engine owning a lock).
func writeHomeFlake(stateDir string, homeNix []byte, staged map[string][]byte, secrets []manifest.HomeManagerSecret) (string, error) {
	ident, err := homeIdentityFn()
	if err != nil {
		return "", err
	}
	name := ident.Username

	dir := filepath.Join(stateDir, "home-manager", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create generated flake dir %q: %w", dir, err)
	}
	if err := os.WriteFile(filepath.Join(dir, "home.nix"), homeNix, 0o644); err != nil {
		return "", fmt.Errorf("write generated home.nix in %q: %w", dir, err)
	}

	// Phase-1 documented-boundary secrets compose with the engine-generated home
	// configuration as a SEPARATE module (./secrets.nix), so they wire uniformly
	// for both settings- and config-mode without touching the user's home.nix. The
	// module contains REFERENCES only (compileSecretsModule never reads material).
	var extraModules []string
	if mod, ok := compileSecretsModule(secrets); ok {
		if err := os.WriteFile(filepath.Join(dir, "secrets.nix"), []byte(mod), 0o644); err != nil {
			return "", fmt.Errorf("write generated secrets.nix in %q: %w", dir, err)
		}
		extraModules = append(extraModules, "./secrets.nix")
	}
	// Stage any extra files (e.g. catalog `files`) beside the flake, binary-safe;
	// they are referenced relatively (./<rel>) so they stay inside the flake tree
	// (pure-eval-safe).
	for rel, content := range staged {
		dest := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return "", fmt.Errorf("create staged dir for %q: %w", rel, err)
		}
		if err := os.WriteFile(dest, content, 0o644); err != nil {
			return "", fmt.Errorf("stage file %q: %w", rel, err)
		}
	}

	spec := HomeFlakeSpec{
		Name:           name,
		Username:       ident.Username,
		HomeDir:        ident.HomeDir,
		StateVersion:   ident.StateVersion,
		System:         nixSystem(),
		NixpkgsPin:     defaultPin(),
		HomeManagerPin: defaultHomePin(),
		ExtraModules:   extraModules,
	}
	if err := os.WriteFile(filepath.Join(dir, "flake.nix"), []byte(renderHomeFlake(spec)), 0o644); err != nil {
		return "", fmt.Errorf("write generated flake.nix in %q: %w", dir, err)
	}

	return dir + "#" + name, nil
}
