// Copyright 2025 Substrate Systems OÜ
// SPDX-License-Identifier: Apache-2.0

package nix

import (
	"sort"
	"strings"

	"github.com/Artexis10/endstate/go-engine/internal/manifest"
)

// compileSecretsModule renders a home-manager module (secrets.nix) that wires the
// Phase-1 documented-boundary secret REFERENCES into the generated home
// configuration. It returns ("", false) when there are no secrets, otherwise the
// module text and true.
//
// THE STRUCTURAL KEYSTONE: this function NEVER reads, embeds, or stages secret
// material. Unlike the catalog `files` map (which os.ReadFile's source content at
// compile time in CompileHomeNix), a secret entry's path/env is emitted as a Nix
// path/string REFERENCE only — there is no code path from a HomeManagerSecret to
// file content. No-embed is therefore true BY CONSTRUCTION:
//   - path → home.file.<homeRelTarget(name)>.source = config.lib.file.mkOutOfStoreSymlink <path>;
//
// Phase 1 is PATH-ONLY; env-exposed secrets are rejected at load (see the
// validator) — in the boundary model the engine never holds a secret's value, so
// it cannot meaningfully set an env var. That is deferred to its own design.
//
// The path is wired via `config.lib.file.mkOutOfStoreSymlink`, which symlinks to
// the user-provisioned path at ACTIVATION time — it does NOT read or import the
// file at eval/build, so the secret never enters the world-readable /nix/store and
// the flake stays pure-eval-safe (a raw absolute path would be forbidden in pure
// eval, and a store import would leak the content). The engine only references
// where the secret lands; the user provisions it out-of-band.
//
// Output is deterministic: secrets are sorted by name before emission.
func compileSecretsModule(secrets []manifest.HomeManagerSecret) (string, bool) {
	if len(secrets) == 0 {
		return "", false
	}

	sorted := make([]manifest.HomeManagerSecret, len(secrets))
	copy(sorted, secrets)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var stmts []string
	for _, s := range sorted {
		switch {
		case s.Path != "":
			// A path entry → home.file.<homeRelTarget>.source references the path via
			// mkOutOfStoreSymlink, which symlinks to the user-provisioned path at
			// ACTIVATION time. It never reads/imports the file at eval/build, so the
			// secret stays out of the /nix/store and the flake remains pure-eval-safe.
			homeRel := homeRelTarget(s.Name)
			stmts = append(stmts, "home.file."+nixString(homeRel)+".source = config.lib.file.mkOutOfStoreSymlink "+nixString(s.Path)+";")
		}
	}
	if len(stmts) == 0 {
		return "", false
	}

	var b strings.Builder
	b.WriteString("# GENERATED BY ENDSTATE — home-manager secret REFERENCES only.\n")
	b.WriteString("# This module references where each secret is expected at activation; it\n")
	b.WriteString("# NEVER contains secret material (the engine stays out of secret plaintext).\n")
	b.WriteString("{ config, ... }:\n{\n")
	for _, st := range stmts {
		b.WriteString("  " + st + "\n")
	}
	b.WriteString("}\n")
	return b.String(), true
}
